### ISSUE TITLE
Drop Python 2.4 compatibility?

### ISSUE THREAD

**Issue by JulienPalard** [cGIfl300/Internet-Speed#1]
It would enhance the maintainability by removing some old cases.

**Comment by cGIfl300** [comment]
Actualy this part is provide by a third party https://github.com/sivel/speedtest-cli .
Using this third party software allow an use as standalone with no external server need (public servers are used instead of a private one).
I guess I won't improve this part so far, it has been made for individual easy use.
This file is obviously ugly but it works fine as a subprocess call.
